version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: pub
    directories: [/, /example]
    schedule:
      interval: monthly
    groups:
      pub:
        patterns: ['*']
