coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        informational: true

ignore:
  - example/**
  - test/**

comment:
  layout: 'diff, files'
  require_changes: true
